
* 作业

** 注册、绑定三个模拟账户，登录账户

** 

** 

** 对商品策略进行测试，了解收益率、收益风险比、调整收益风险比、盈亏比、夏普比率、最大资产回撤等指标意义

*** 收益率
    
**** 基本信息
     收益率是指投资的回报率，一般以年度百分比表达，根据当时市场价格、面值、息票利率以及距离到期日时间计算。对公司而言，
     收益率指净利润占使用的平均资本的百分比。收益率研究的是收益率作为一项个人（以及家庭）和社会（政府公共支出）投资的收益率的大小，
     可以分为个人收益率与社会收益率，主要关注的是前者。

**** 决定因素
     在市场经济中有四个决定收益率的因素：
     1. 资本商品的生产率，即对煤矿、大坝、公路、桥梁、工厂、机器和存货的预期收益率。
     2. 资本商品生产率的不确定程度。
     3. 人们的时间偏好，即人们对即期消费与未来消费的偏好。
     4. 风险厌恶，即人们为减少风险暴露而愿意放弃的部分。
     
**** 收益率的公式：
    
     Earnings Yield = Earnings / Market Capitalization
     
     Earnings Yield = Net Profit / Market Cap

*** 收益风险比

**** 基本信息
     成功者会同时考虑收益和风险，因为投资和投机都不是赌博，赌博是一本一利的，输赢是相同的，但投资和投机则不一样，应该追求小投入高回报，
     所以要同时考虑收益和风险，衡量收益和风险的指标就是收益风险比

**** 计算公式
     收益风险比=可能收益/可能损失

**** 举例
     亏损时不可避免的，重点是我们要做到大赚小赔，而不是小赚大赔，收益风险比就是不错的衡量指标。
     + 假设做了 4 次，3 次亏光，1 次赚了 300%，收益风险比就是 3:1，那么总收益率：
       300%*1-100%*3 = 0，这就是所谓的“一赚抵三赔”。

     + TradeBlazer 软件中:
       收益风险比 = 年化净利润 / 最大资产回撤

*** 调整收益风险比
    
**** 举例
     TradeBlazer 软件中：
     调整收益风险比 =   年化净利润 / 平均资产回撤
     平均资产回撤 = 大于等于最大资产基准回撤基准线 回撤值 的总和 / 大于等于最大资产基准回撤基准线的次数

*** 盈亏比
    总盈亏 = 赢的所有次数 *赢的平均金额 - 输的所有次数 * 输的平均金额
    胜率比 = 赢的所有次数 / 总次数 * 100% 
    盈亏比 = 赢的平均金额 / 输的平均金额

*** 夏普比率

**** 说明
     夏普比率就是一个可以同时对收益与风险加以综合考虑的三大经典指标之一。 
     投资中有一个常规的特点，即投资标的的预期报酬越高，投资人所能忍受的波动风险越高；
     反之，预期报酬越低，波动风险也越低。所以理性的投资人选择投资标的与投资组合的主要目的为：
     在固定所能承受的风险下，追求最大的报酬；或在固定的预期报酬下，追求最低的风险。

**** 计算公式
     #+BEGIN_SRC latex
       \begin{equation}
         Sp = \frac{E(R_p)-R_f}{\sigma_p}
       \end{equation}
       #+END_SRC
     其中， $E(R_p)$ 表示投资组合预期报酬率； $R_f$ 为无风险利率； $\sigma_p$ 表示投资组合标准差

**** 注意
     夏普比率在运用中应该注意的问题夏普比率在计算上尽管非常简单，但在具体运用中仍需要对夏普比率的适用性加以注意：
     1、用标准差对收益进行风险调整，其隐含的假设就是所考察的组合构成了投资者投资的全部。因此只有在考虑在众多的基金中选择购买某一只基金时，夏普比率才能够作为一项重要的依据；
     2、使用标准差作为风险指标也被人们认为不很合适的。
     3、夏普比率的有效性还依赖于可以以相同的无风险利率借贷的假设；
     4、夏普比率没有基准点，因此其大小本身没有意义，只有在与其他组合的比较中才有价值；
     5、夏普比率是线性的，但在有效前沿上，风险与收益之间的变换并不是线性的。因此，夏普指数在对标准差较大的基金的绩效衡量上存在偏误
     6、夏普比率未考虑组合之间的相关性，因此纯粹依据夏普值的大小构建组合存在很大问题；
     7、夏普比率与其他很多指标一样，衡量的是基金的历史表现，因此并不能简单地依据基金的历史表现进行未来操作。
     8、计算上，夏普指数同样存在一个稳定性问题：夏普指数的计算结果与时间跨度和收益计算的时间间隔的选取有关。
     尽管夏普比率存在上述诸多限制和问题，但它仍以其计算上的简便性和不需要过多的假设条件而在实践中获得了广泛的运用。
     基金较高的净值增长率可能是在承受较高风险的情况下取得的，因此仅仅根据净值增长率来评价基金的业绩表现并不全面，衡量基金表现必须兼顾收益和风险两个方面，夏普比率就是一个可以同时对收益与风险加以综合考虑的指标。夏普比率又被称为夏普指数，由诺贝尔奖获得者威廉·夏普于 1966 年最早提出，目前已成为国际上用以衡量基金绩效表现的最为常用的一个标准化指标。

*** 最大资产回撤
    最大回撤主要有两种：一种是历史回溯后的最大回撤，一种是对未来的预期最大回撤。历史最大回撤就是在某个时间段上，收益率最低的那个数值；对未来的预期最大回撤，就是在某个置信区间下，未来最大回撤的值是多少
